"""empty message

Revision ID: 6a658187329f
Revises: ab76b96f1200
Create Date: 2018-12-07 11:56:55.800114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a658187329f'
down_revision = 'ab76b96f1200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amnioticrecord', 'records',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('amnioticrecord', 'wife_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('amnioticrecord', 'wife_birthday_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('amnioticrecord', 'wife_birthday_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('amnioticrecord', 'wife_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('amnioticrecord', 'wife_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('amnioticrecord', 'wife_birthday_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('amnioticrecord', 'wife_birthday_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('amnioticrecord', 'wife_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('amnioticrecord', 'records',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
